### ISSUE TITLE
Feature: support nested destructure

### ISSUE THREAD

**Issue by nirtamir2** [nirtamir2/eslint-plugin-sort-destructure-keys-typescript#3]
Feature: support nested destructure
Suggested here https://github.com/mthadley/eslint-plugin-sort-destructure-keys/issues/299#issuecomment-2268595913

For this nested destructure
```ts
type Nested = {
  a1: { a21: string; a22: string };
  b1: { b21: string; b22: string };
};

export function Example(props: Nested) {
  const {
    b1: { b22, b21 },
    a1: { a22, a21 },
  } = props;
}

```
The fix should be
```ts
type Nested = {
  a1: { a21: string; a22: string };
  b1: { b21: string; b22: string };
};

export function Example(props: Nested) {
  const {
    a1: { a21, a22 },
    b1: { b21, b22 },
  } = props;
}

```

**Comment by gabriel-calin-lazar** [comment]
@nirtamir2 any updates on this one ? almost 5 months since the issue was opened

**Comment by nirtamir2** [comment]
Hi @gabriel-calin-lazar,

Thanks for following up! I’ve partially implemented this feature but haven’t finished it yet, as I’ve been trying to better understand its practical value. Personally, I don’t often use nested destructuring. Could you share a real-world example where this functionality would be helpful?

Additionally, I noticed that the plugin currently has less than 50 downloads per month and only one star. This makes me curious about the broader demand for this feature. Do you think it’s worth prioritizing, given the current usage of the repo?

**Comment by nirtamir2** [comment]
Done in 0.0.4

**Comment by gabriel-calin-lazar** [comment]
the rule does not seem to consider default values being provided to any destructured level. in the image provided, all not highlighed should be highlighted, but are not - because of default values being provided during destructuring. is this a know limitation, or should it have already been covered  ?

![Image](https://github.com/user-attachments/assets/c536fee8-f619-45e4-be68-d00879a165b3)

**Comment by nirtamir2** [comment]
Got it. I added support to default values now. You can see it in version `0.0.5`. 

> the rule does not seem to consider default values being provided to any destructured level. in the image provided, all not highlighed should be highlighted, but are not - because of default values being provided during destructuring. is this a know limitation, or should it have already been covered ?
> 
> ![Image](https://github.com/user-attachments/assets/c536fee8-f619-45e4-be68-d00879a165b3)

**Comment by gabriel-calin-lazar** [comment]
there are still issues when default values are provided and even when optional properties are being destructured

![Image](https://github.com/user-attachments/assets/7cb447a7-d479-45e1-b02a-0ddefea3a525)

![Image](https://github.com/user-attachments/assets/b8364e8e-66a2-4207-a3ec-80c30b134384)

**Comment by nirtamir2** [comment]
So it seems like a messaging issue because from the images the report is
good. Will fix soon

**Comment by nirtamir2** [comment]
Try now in 0.0.6

**Comment by gabriel-calin-lazar** [comment]
Nope. The issues are stil present in 0.0.6

See screenshots. All examples should be highlighted

There are no highlights 
- > for when both destructuring and default values are in use
- > for when destructuring and optional member

![Image](https://github.com/user-attachments/assets/eb54e6fe-b2d9-4a05-b08a-ec3e85ad3496)

![Image](https://github.com/user-attachments/assets/fd08f121-b85f-4105-b91d-c9ef70452d65)

**Comment by nirtamir2** [comment]
Fixed in eslint-plugin-sort-destructure-keys-typescript@0.0.8 by https://github.com/nirtamir2/eslint-plugin-sort-destructure-keys-typescript/pull/7

**Comment by gabriel-calin-lazar** [comment]
I have bumped up to be able to use 0.0.8, but the issue still remains, even though I see that specific tests have been added to cover for this specific case - 'nested object destructuring with default values'.  Am I missing something ? is there any specific lint rule config required on my side ?

**Comment by nirtamir2** [comment]
No - you're right. Added this test case. 

Fixed in eslint-plugin-sort-destructure-keys-typescript@0.1.0 (I added a new rule `sort-jsx-attributes-by-type` in this version too if you are interested)

**Comment by gabriel-calin-lazar** [comment]
based on [these](https://github.com/nirtamir2/eslint-plugin-sort-destructure-keys-typescript/compare/v0.1.0...v0.2.0#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R21) changes - for version 0.2.0 - require imports - cjs - are no longer supported ? is this intended ?

**Comment by nirtamir2** [comment]
> based on [these](https://github.com/nirtamir2/eslint-plugin-sort-destructure-keys-typescript/compare/v0.1.0...v0.2.0#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R21) changes - for version 0.2.0 - require imports - cjs - are no longer supported ? is this intended ? i want to get the use the rule released in 0.2.0 - sort-object-properties-by-type - but I cannot. As the previous setup I had is no longer working for 0.2.0 - but it was working for - 0.1.0

Yes, this is intentional. What issue are you facing with the ESM version? Are you unable to switch to it? I followed a similar approach to [this change](https://github.com/antfu/eslint-plugin-antfu/commit/126bf44e0c28a061ed05de3db708ca7c121f5027)

**Comment by gabriel-calin-lazar** [comment]
Previously, all I had to do to make use of the destructure rule was this

<img width="701" alt="Image" src="https://github.com/user-attachments/assets/723830c9-f919-4ce0-99c3-e998fe266570" />

<img width="809" alt="Image" src="https://github.com/user-attachments/assets/6ea02dfd-44c1-4868-a3da-71e74b44a89e" />

After upgrading to 0.2.0 this simple setup stops working

**Comment by nirtamir2** [comment]
Can you upgrade to ESLint 9?
They change the way we load ESLint plugins with flat config

**Comment by gabriel-calin-lazar** [comment]
> Can you upgrade to ESLint 9? They change the way we load ESLint plugins with flat config

Not just yet. Have been delaying this particular upgrade for quite some time. Any chance to support both ESLint 9 and ESLint 8 ? To not have to force an upgrade to be able to use 0.2.0 and onward.

**Comment by gabriel-calin-lazar** [comment]
returning the CJS would allow easy integration for all still on ESLint 8 - with no short term plans on upgrading to ESLint 9.
not returning the CJS would allow integration only for those already on  ESLint 9, or usage up until 0.1.0 when CJS was still supported

**Comment by nirtamir2** [comment]
@gabriel-calin-lazar 
Please check https://github.com/nirtamir2/eslint-plugin-sort-destructure-keys-typescript/pull/12#issuecomment-2700137299
If it works for you with your ESLint config, I'll merge it and bump a version

**Comment by gabriel-calin-lazar** [comment]
It all works with that specific commit. both rules. thanks

**Comment by nirtamir2** [comment]
Added in `0.3.0`
